<?php

namespace Modules\CatalogDelivery\Database\Seeders;

class CatalogInventory
{
    public const IMAGES = [
        'photo-1496181133206-80ce9b88a853',
        'photo-1523275335684-37898b6baf30',
        'photo-1516035069371-29a1b244cc32',
        'photo-1511707171634-5f897ff02aa9',
        'photo-1505740420928-5e560c06d30e',
        'photo-1594932224010-77f3ad36bc3d',
        'photo-1549298916-b41d501d3772',
        'photo-1539008835158-a3f2d226a26a',
        'photo-1584917865442-de89df76afd3',
        'photo-1521572267360-ee0c2909d518',
        'photo-1555041469-a586c61ea9bc',
        'photo-1507473885765-e6ed057f782c',
        'photo-1592078615290-033ee584e267',
        'photo-1517668808822-9ebb02f2a0e6',
        'photo-1578500494198-246f612d3b3d',
        'photo-1589998059171-988d887df646',
        'photo-1507842217343-583bb7270b66',
        'photo-1544947950-fa07a98d237f',
    ];

    /**
     * Category => [name, IMAGES index][]. 15 items per category; pools larger
     * than 15 (Electronics, Home & Kitchen) cover pre-existing extra rows.
     */
    public const CATALOG = [
        'Electronics' => [
            ['Aether Pro Laptop', 0],
            ['Chronos Gold Watch', 1],
            ['Zenith Studio Cam', 2],
            ['Nova Mobile 12', 3],
            ['Vector Pods Max', 4],
            ['Pulse Wireless Earbuds', 4],
            ['Orbit Desk Speaker', 4],
            ['Vertex Mechanical Keyboard', 0],
            ['Prism 4K Monitor', 0],
            ['Lumen Smart Lamp', 1],
            ['Drift Bluetooth Speaker', 4],
            ['Atlas Quadcopter Drone', 2],
            ['Volt GaN Charger', 3],
            ['Echo Smart Display', 0],
            ['Titan Gaming Console', 0],
            ['Slate E-Reader', 2],
            ['Nova Power Bank', 3],
            ['Cascade Action Camera', 2],
            ['Vertex Webcam Pro', 0],
            ['Prism LED Strip Kit', 1],
        ],
        'Clothing' => [
            ['Imperial Silk Suit', 5],
            ['Vanguard Leather Boots', 6],
            ['Elysian Evening Gown', 7],
            ['Nomad Leather Carryall', 8],
            ['Aura Linen Set', 9],
            ['Alpine Wool Coat', 5],
            ['Mariner Canvas Jacket', 9],
            ['Solstice Denim Jacket', 9],
            ['Atlas Trail Sneakers', 6],
            ['Horizon Wool Scarf', 5],
            ['Cascade Rain Shell', 7],
            ['Oasis Cotton Shirt', 9],
            ['Terra Hiking Pants', 9],
            ['Ember Knit Sweater', 5],
            ['Drift Swim Trunks', 9],
        ],
        'Home & Kitchen' => [
            ['Nordic Pine Sofa', 10],
            ['Eclipse Sphere Lamp', 11],
            ['Studio Oak Chair', 12],
            ['Minimalist Coffee Maker', 13],
            ['Ceramic Bloom Vase', 14],
            ['Linen Duvet Set', 15],
            ['Copper Tea Kettle', 13],
            ['Rustic Oak Dining Table', 10],
            ['Marble Cutting Board', 15],
            ['Brass Table Clock', 1],
            ['Woven Jute Rug', 15],
            ['Cast Iron Skillet', 13],
            ['Glass Pitcher Set', 14],
            ['Velvet Throw Pillow', 15],
            ['Walnut Book Stand', 15],
            ['Porcelain Dinner Set', 14],
            ['Bamboo Plant Stand', 15],
            ['Aroma Oil Diffuser', 11],
            ['Frosted Mason Jar Set', 14],
            ['Walnut Spice Rack', 15],
        ],
        'Books' => [
            ['The Art of Minimalism', 15],
            ['Architectural Digest — Collector\'s Edition', 16],
            ['Luxury Living Vol. 1', 17],
            ['The Craft of Design', 15],
            ['Timeless Interiors', 16],
            ['Modern Architecture in Focus', 16],
            ['The Art of Tea', 15],
            ['Slow Living Journal', 15],
            ['The Coffee Atlas', 17],
            ['Handmade Craftsmanship', 17],
            ['The Design of Everyday Things', 15],
            ['Color Theory for Creatives', 16],
            ['The Story of Ceramics', 15],
            ['Urban Sketching Guide', 16],
            ['The Complete Photographer', 17],
        ],
        'Beauty & Wellness' => [
            ['Rose Quartz Facial Roller', 15],
            ['Lavender Sleep Mist', 14],
            ['Argan Oil Serum', 14],
            ['Dead Sea Salt Scrub', 15],
            ['Bamboo Toothbrush Set', 15],
            ['Silk Sleep Mask', 9],
            ['Cedar Beard Oil', 15],
            ['Citrus Body Butter', 15],
            ['Eucalyptus Bath Salts', 14],
            ['Aloe Hydrating Gel', 14],
            ['Charcoal Face Mask', 15],
            ['Jasmine Hair Oil', 14],
            ['Chamomile Tea Blend', 15],
            ['Peppermint Foot Cream', 15],
            ['Vitamin C Brightening Drops', 14],
        ],
        'Sports & Outdoors' => [
            ['Alpine Trekking Poles', 12],
            ['Carbon Road Helmet', 6],
            ['Yoga Mat Pro', 9],
            ['Insulated Water Bottle', 13],
            ['Trail Running Shoes', 6],
            ['Camping Hammock', 9],
            ['All-Terrain Skateboard', 10],
            ['Adjustable Dumbbell Set', 10],
            ['Resistance Band Kit', 9],
            ['LED Bike Lights', 1],
            ['Portable Camping Stove', 13],
            ['Waterproof Backpack', 8],
            ['Climbing Chalk Bag', 9],
            ['Folding Camp Chair', 12],
            ['Swim Training Fins', 6],
        ],
        'Toys & Games' => [
            ['Wooden Building Blocks', 15],
            ['Chess Set Deluxe', 15],
            ['Puzzle Adventure Box', 16],
            ['Remote Control Drone', 2],
            ['Plush Moon Bear', 15],
            ['Card Game Night Pack', 15],
            ['Magnetic Building Tiles', 15],
            ['Strategy Board Game', 16],
            ['Watercolor Painting Kit', 15],
            ['Mini Racing Car Set', 3],
            ['Storybook Collection Vol. 2', 15],
            ['Building Brick Tower', 0],
            ['Jigsaw Map of the World', 16],
            ['Robot Coding Kit', 0],
            ['Musical Keyboard Toy', 0],
        ],
    ];

    public static function namesFor(string $category): array
    {
        return array_map(fn ($item) => $item[0], self::CATALOG[$category]);
    }
}